workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Disable Swift Package Manager
        script: |
          flutter config --no-enable-swift-package-manager
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist /tmp/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
